[profile.default]
names = true
sizes = true
libs = ["node_modules", "lib"]
fs_permissions = [{ access = "read", path = "./config/" }]
gas_limit = "18446744073709551615"
evm_version = "cancun"
optimizer = true
optimizer_runs = 200

[profile.build]
evm_version = "paris"

[fuzz]
runs = 32

[invariant]
runs = 4
depth = 64

[rpc_endpoints]
mainnet = "https://eth-mainnet.g.alchemy.com/v2/${ALCHEMY_KEY}"
avalanche = "https://rpc.ankr.com/avalanche"
tenderly = "https://mainnet.gateway.tenderly.co/5jAnxSxmcVvFtPzEWPk5rc"
# tenderly = "https://sepolia.gateway.tenderly.co/3ICr3uFynN0R0o8kfTFdeX"
# tenderly = "https://virtual.mainnet.eu.rpc.tenderly.co/51b1f545-0fb7-48fb-bef9-2ff383512332"
# tenderly = "https://rpc.tenderly.co/fork/${TENDERLY_FORK_ID}"

# HyperEVM / Hyperlend
# hyperevm_mainnet = "https://hyperliquid-mainnet.g.alchemy.com/v2/${ALCHEMY_HYPEREVM_KEY}"
# hyperevm_testnet = "https://hyperliquid-testnet.g.alchemy.com/v2/${ALCHEMY_HYPEREVM_KEY}"
hyperevm_mainnet = "https://rpc.hyperliquid.xyz/evm"
hyperevm_testnet = "https://rpc.hyperliquid-testnet.xyz/evm"
#hyperevm_mainnet = "https://rpc.hyperlend.finance"

# See more config options https://github.com/foundry-rs/foundry/tree/master/crates/config
